[theme]
primaryColor="#f17f20"
backgroundColor="#6f0049"
secondaryBackgroundColor="#000000"
textColor="#ffffff"
font="monospace"

[server]
head = """
<title>Zauberpass - Euro</title>
<link rel="icon" type="image/x-icon" href="https://raw.githubusercontent.com/mhassan2048/Zauberpass/main/.streamlit/favicon.ico">
"""
